# Use root/example as user/password credentials
# docker-compose up
version: '3.1'

services:
    adminer:
      image: adminer
      restart: always
      ports:
        - 8099:8080

    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: db_data_123
      ports:
        - 3307:3306

    php74_apache:
      build:
        context: ./.docker
      volumes:
        - .apache/:/etc/apache2/v-host/
        - ./www:/var/www
        - .php/debug-lms.ini:/usr/local/etc/php/conf.d/debug-lms.ini
      ports:
        - 80:80
